name: restaurant_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0-nullsafety
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_rating_bar: ^4.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  google_maps_flutter: ^2.2.3
  # geoflutterfire: ^3.0.3
  select_form_field:
    git:
      url: "https://github.com/tidianeb5/select_form_field.git"
  flutter_gradient_colors: ^2.0.0-prerelease-nullsafety
  # location: ^4.1.1
  url_launcher: ^6.0.2
  webview_flutter: ^4.0.1 #breaking changes
  lottie: ^1.0.1
  flutter_hooks: ^0.16.0
  introduction_screen: ^2.0.0
  photo_view: ^0.13.0
  cached_network_image: ^3.0.0-nullsafety

  octo_image: ^1.0.0-nullsafety.1
  uuid: ^3.0.1
  timeago: ^3.0.2
  intl: ^0.17.0
  package_info: ^2.0.0 #outdated
  content_placeholder:
    git:
      url: "https://github.com/wiseminds/content-placeholder.git"
  # Validation and forms
  form_field_validator: ^1.1.0
  geolocator: ^7.0.1 #breakchange : config
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  # Auth
  google_sign_in: ^5.3.2
  # Firebase
  firebase_core: ^2.4.1
  firebase_dynamic_links: ^5.0.11
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  # Stacked Architecture
  stacked: ^2.3.15
  stacked_services: ^0.8.26
  # observable_ish: ^4.0.6
  injectable: ^1.2.0
  rxdart: ^0.27.4
  scrollable_positioned_list: ^0.3.5

  map_launcher: ^2.2.3
  flutter_facebook_auth: ^4.3.4+1
  image_picker: ^0.8.5+3
  share_plus: ^6.3.1
  geoflutterfire2: ^2.3.12
  algolia: ^1.1.1
  flutter_dotenv: ^5.0.2
  firebase_messaging: ^14.2.5
  flutter_local_notifications: ^8.2.0
  cloud_functions: ^4.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  logger: ^1.0.0
  import_sorter: ^4.4.2
  flutter_launcher_icons: ^0.9.0
  build_runner:
  stacked_generator:

flutter_icons:
  android: "ic_launcher"
  # ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/logo_icons/
    - assets/fonts/
    - assets/animations/
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/cera/Cera_Pro_Medium.ttf
        - asset: assets/fonts/cera/Cera_Pro_Regular_Italic.ttf
          style: italic
        - asset: assets/fonts/cera/Cera_Pro_Black.ttf
          weight: 900
        - asset: assets/fonts/cera/Cera_Pro_Bold.ttf
          weight: 700
        - asset: assets/fonts/cera/Cera_Pro_Black_italic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/cera/Cera_Pro_Light.ttf
          weight: 200
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
